services:
  jupyterlab:
    image: gdpimage
    env_file:
      - .env
    ports:
      - "8890:8888"
      - "8050:8050"
    volumes: 
      - ./:/Project_GDP
      - ./settings.txt:/root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
    networks:
      - GDPnetwork
  postgres:
    image: postgres:latest
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - GDPnetwork

  mongo:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongodata:/data/GDPnetwork
    ports:
      - "27017:27017"
    networks:
      - GDPnetwork

volumes:
  postgresdata:
  mongodata:

networks:
  GDPnetwork: